# ASSIGNMENT 1 - Applied Data Science
## Hiya Kulasrestha - 20BCE2828
## VIT, Vellore

### Q1. Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [30]:
name = "Hiya Kulasrestha"
age = 20

print("My name is ", name)
print("My age is ", age)

My name is  Hiya Kulasrestha
My age is  20


### Q2. X = "Datascience is used to extract meaningful insights." 
### Split the string.

In [31]:
x = "Datascience is used to extract meaningful insights."

new_x = x.split()
print(new_x)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


### Q3. Make a function that gives multiplication of two numbers

In [32]:
def mul(a,b):
    c=a*b
    print(c)

mul(4,5)

20


### Q4. Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [33]:
x = {'Maharashtra' : 'Mumbai', 'West Bengal' : 'Kolkata', 'Tamil Nadu': 'Chennai', 'Karnataka' : 'Bangalore', 'Assam' : 'Dispur'}

print(x.items())
print(x.keys())
print(x.values())

dict_items([('Maharashtra', 'Mumbai'), ('West Bengal', 'Kolkata'), ('Tamil Nadu', 'Chennai'), ('Karnataka', 'Bangalore'), ('Assam', 'Dispur')])
dict_keys(['Maharashtra', 'West Bengal', 'Tamil Nadu', 'Karnataka', 'Assam'])
dict_values(['Mumbai', 'Kolkata', 'Chennai', 'Bangalore', 'Dispur'])


### Q5. Create a list of 1000 numbers using range function.

In [34]:
x = list(range(1,1001))

##print(x)
print(len(x))

1000


### Q6. Create an identity matrix of dimension 4 by 4

In [35]:
import numpy as np
x = np.eye(4)

print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Q7. Create a 3x3 matrix with values ranging from 1 to 9

In [36]:
x =  np.arange(1, 10).reshape(3,3)

print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q8. Create 2 similar dimensional array and perform sum on them.

In [37]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(11,20).reshape(3,3)

z = x + y
print("x = \n", x)
print("\ny = \n", y)
print("\nx + y = \n", z)

x = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

y = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

x + y = 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


### Q9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [38]:
import datetime
import pandas as pd

start_date = datetime.datetime.strptime("01-02-2023", "%d-%m-%Y")
end_date = datetime.datetime.strptime("01-03-2023", "%d-%m-%Y")

date_list = pd.date_range(start_date, end_date, freq='D')

print(date_list)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


### Q10. Given a dictionary, convert it into corresponding dataframe and display it
### dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [39]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales' : [250, 200, 240]}

df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
